package GUI;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Shape;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import shapes.Shapes;

public class GUI_main extends javax.swing.JFrame {

    public final JFileChooser filechooser;
    ArrayList<Shapes> shapeList = new ArrayList<>();

    DefaultListModel dlm = new DefaultListModel();

    public GUI_main() {
        initComponents();
        filechooser = new JFileChooser();  // Line of code
        filechooser.setCurrentDirectory(new File("."));
        filechooser.setFileFilter(new FileNameExtensionFilter(".txt", "txt"));
        adder.setVisible(false);
        list.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        logdata = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        parameter = new javax.swing.JTextArea();
        area = new javax.swing.JTextField();
        volume = new javax.swing.JTextField();
        gw = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adder = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        newParam = new javax.swing.JTextField();
        addShape = new javax.swing.JButton();
        closepanel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        create = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        showfolder = new javax.swing.JMenuItem();
        updateSession = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        delete = new javax.swing.JMenuItem();
        clear = new javax.swing.JMenuItem();
        createshape = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROJECT SHAPE v1.0");
        setBackground(new java.awt.Color(251, 250, 190));
        setPreferredSize(new java.awt.Dimension(1500, 800));

        list.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        logdata.setColumns(20);
        logdata.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        logdata.setRows(5);
        jScrollPane2.setViewportView(logdata);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Shape List");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Shape Properties");

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setPreferredSize(new java.awt.Dimension(90, 30));

        parameter.setColumns(20);
        parameter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parameter.setRows(5);
        jScrollPane3.setViewportView(parameter);

        area.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        area.setPreferredSize(new java.awt.Dimension(90, 30));

        volume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volume.setPreferredSize(new java.awt.Dimension(90, 30));
        volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeActionPerformed(evt);
            }
        });

        gw.setBackground(new java.awt.Color(255, 255, 255));
        gw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gw.setPreferredSize(new java.awt.Dimension(800, 400));

        javax.swing.GroupLayout gwLayout = new javax.swing.GroupLayout(gw);
        gw.setLayout(gwLayout);
        gwLayout.setHorizontalGroup(
            gwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        gwLayout.setVerticalGroup(
            gwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jLabel3.setText("NAME");

        jLabel4.setText("PARAMETERS");

        jLabel6.setText("VOLUME");

        jLabel7.setText("AREA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Log History:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Graphics Window");

        adder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("NAME:");

        newName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameActionPerformed(evt);
            }
        });

        jLabel11.setText("PARAMETERS: ( X,Y,side..../x1,x2...,y1,y2....)");

        addShape.setText("Add");
        addShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShapeActionPerformed(evt);
            }
        });

        closepanel.setText("Close");
        closepanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closepanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adderLayout = new javax.swing.GroupLayout(adder);
        adder.setLayout(adderLayout);
        adderLayout.setHorizontalGroup(
            adderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newParam, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addShape)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closepanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adderLayout.setVerticalGroup(
            adderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10)
                .addComponent(jLabel11)
                .addComponent(newParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addShape)
                .addComponent(closepanel))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        file.setText("File");
        file.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        file.add(open);

        create.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        create.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        create.setText("Create File");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        file.add(create);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        save.setText("Save Result");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        file.add(save);

        showfolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        showfolder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showfolder.setText("Open File Location");
        showfolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showfolderActionPerformed(evt);
            }
        });
        file.add(showfolder);

        updateSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateSession.setText("Save Session");
        updateSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSessionActionPerformed(evt);
            }
        });
        file.add(updateSession);

        exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        edit.setText("Edit");
        edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setText("Delete item");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        edit.add(delete);

        clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clear.setText("Clear window");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        edit.add(clear);

        createshape.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        createshape.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createshape.setText("Add shape");
        createshape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createshapeActionPerformed(evt);
            }
        });
        edit.add(createshape);

        jMenuBar1.add(edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel3))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(65, 65, 65))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(volume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(area, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel9)
                                .addGap(423, 423, 423)
                                .addComponent(jLabel2)
                                .addGap(0, 113, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(jLabel5))
                                    .addComponent(gw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane1))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String entry1 = name.getText();      // name of shape
        String entry2 = parameter.getText(); // parameters of shape
        String entry3 = area.getText();      // area
        String entry4 = volume.getText();    // volume
        try {
            PrintWriter resultprinter = new PrintWriter("Results.txt");
            File resultfile = new File("C:\\Users\\Gautam Ghosh\\Documents\\NetBeansProjects\\Shapes\\Results.txt");
            if (resultfile.length() == 0) {
                resultprinter.write("/-----------------RESULTS------------------/");
                resultprinter.write(" " + "\n");
                resultprinter.write(" " + "\n");
                resultprinter.write("\n" + "Name: " + entry1 + "\n" + " " + "\n" + "Parameters: " + "\n" + entry2 + "\n" + " " + "\n" + "Area: " + entry3 + "\n" + " " + "\n" + "Volume: " + entry4 + "\n");
                resultprinter.write(" " + "\n");
                resultprinter.write("/-------------------END--------------------/");
                resultprinter.close();
            } else {
                resultprinter.write(" " + "\n");
                resultprinter.write("/------------------------------------------/");
                resultprinter.write(" " + "\n");
                resultprinter.write(" " + "\n");
                resultprinter.write("\n" + "Name: " + entry1 + "\n" + " " + "\n" + "Parameters: " + "\n" + entry2 + "\n" + " " + "\n" + "Area: " + entry3 + "\n" + " " + "\n" + "Volume: " + entry4 + "\n");
                resultprinter.write(" " + "\n");
                resultprinter.write("/-------------------END--------------------/");
                resultprinter.close();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        File newfile = new File("C:\\Users\\Gautam Ghosh\\Documents\\NetBeansProjects\\Shapes\\newfile.txt");
        try {
            newfile.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(GUI_main.class.getName()).log(Level.SEVERE, null, ex);
        }
        newfile.setWritable(true);
        try {
            Desktop.getDesktop().open(new java.io.File("C:\\Users\\Gautam Ghosh\\Documents\\NetBeansProjects\\Shapes\\newfile.txt"));
        } catch (IOException ex) {
            Logger.getLogger(GUI_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int exitval = JOptionPane.showConfirmDialog(null, "Do you want to exit application? Unsaved changes will be lost!", "exit application", JOptionPane.YES_NO_OPTION);
        if (exitval == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // Let the user select text file, if successful name of text file will be displayed in log file
        int userDecision = filechooser.showOpenDialog(this);
        if (userDecision == JFileChooser.APPROVE_OPTION) {
            File userFile = filechooser.getSelectedFile();
            logdata.append("File: " + userFile.getName() + " opened successfully!" + "\n");

            try {
                Scanner fileScanner = new Scanner(new FileReader(userFile));
                while (fileScanner.hasNext()) {
                    String temp = fileScanner.next();
                    dlm.addElement(temp);
                    Class cls = Class.forName("Shapes." + temp);
                    Shapes s = (Shapes) cls.getConstructor(ArrayList.class).newInstance(convertTexttoDouble(fileScanner.nextLine()));
                    shapeList.add(s);
                    dlm.addElement(s.getClass().getSimpleName());
                }
            } catch (FileNotFoundException | ClassNotFoundException | NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
                Logger.getLogger(GUI_main.class.getName()).log(Level.SEVERE, null, ex);
            }
            logdata.append("Click on a shape to compute Area and Volume." + "\n");
            Graphics g = gw.getGraphics();
            gw.update(g);
            for (int jj = 0; jj < shapeList.size(); jj++) {
                shapeList.get(jj).draw(g);
            }
        }
    }//GEN-LAST:event_openActionPerformed

    private ArrayList<Double> convertTexttoDouble(String line) {
        ArrayList<Double> doubles = new ArrayList<>();
        String[] text = line.split(" ");
        for (int ii = 1; ii < text.length; ii++) {
            doubles.add(Double.parseDouble(text[ii]));
        }
        return doubles;
    }

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        String selection = list.getSelectedValue();
        int index = list.getSelectedIndex();
        name.setText(selection);

//        Class newclass;
//        try {
//            newclass = Class.forName("shapes." + selection);
//            Field identifier = newclass.getField("identity");
//            identifier.setAccessible(true);
//            String[] identify = (String[]) identifier.get(null);
//            Shapes sc; //**
//            Constructor newconst = newclass.getConstructor(String.class);
//            sc = (Shapes) newconst.newInstance(parameterList.get(index));
//            area.setText(Double.toString(sc.Area()));
//            volume.setText(Double.toString(sc.Volume()));
//            String[] temp = parameterList.get(index).split(" ");
//            String[] temp2 = {"X", "Y"};
//            parameter.setText(" ");
//            for (int f = 0; f < 2; f++) {
//                parameter.append(temp2[f] + ": " + temp[f + 1] + "\n");
//            }
//            for (int i = 0; i < identify.length; i++) {
//                parameter.append(identify[i] + ": " + temp[i + 3] + "\n");
//            }
//            Graphics g = gw.getGraphics();
//            gw.update(g);
//            sc.draw(g);
//            logdata.append("Shape:" + selection + " generated sucessfully!" + "\n");
//        } catch (ClassNotFoundException | NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException | NoSuchMethodException | InstantiationException | InvocationTargetException ex) {
//            Logger.getLogger(GUI_main.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_listMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
//        int del_index = list.getSelectedIndex();
//        String delname = list.getSelectedValue();
//        nameList.remove(del_index);
//        parameterList.remove(del_index);
//        String[] newnameList = nameList.toArray(new String[nameList.size()]);
//        list.setListData(newnameList);
//        name.setText(" ");
//        parameter.setText(" ");
//        area.setText(" ");
//        volume.setText(" ");
//        logdata.append(delname + " has been deleted!" + "\n");
    }//GEN-LAST:event_deleteActionPerformed

    private void createshapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createshapeActionPerformed
        adder.setVisible(true);
    }//GEN-LAST:event_createshapeActionPerformed

    private void newNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNameActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void addShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShapeActionPerformed
//        String addname = newName.getText();
//        String addparam = " " + newParam.getText();
//        nameList.add(addname);
//        parameterList.add(addparam);
//        String[] add = nameList.toArray(new String[nameList.size()]);
//        list.setListData(add);
//        logdata.append("New " + addname + " has been added." + "\n");
    }//GEN-LAST:event_addShapeActionPerformed

    private void closepanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closepanelActionPerformed
        adder.setVisible(false);
    }//GEN-LAST:event_closepanelActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        name.setText(" ");
        parameter.setText(" ");
        area.setText(" ");
        volume.setText(" ");
        logdata.setText(" ");
        list.removeAll();
        gw.repaint();
    }//GEN-LAST:event_clearActionPerformed

    private void showfolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showfolderActionPerformed
        try {
            Desktop.getDesktop().open(new java.io.File("."));
        } catch (IOException ex) {
            Logger.getLogger(GUI_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showfolderActionPerformed

    private void updateSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSessionActionPerformed
//        ListModel<String> k = list.getModel();
//        int j = k.getSize();
//        try {
//            PrintWriter session = new PrintWriter("Session.txt");
//            for (int g = 0; g < j; g++) {
//                session.append(nameList.get(g) + "" + parameterList.get(g) + "\n");
//            }
//            session.close();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(GUI_main.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_updateSessionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addShape;
    private javax.swing.JPanel adder;
    private javax.swing.JTextField area;
    private javax.swing.JMenuItem clear;
    private javax.swing.JButton closepanel;
    private javax.swing.JMenuItem create;
    private javax.swing.JMenuItem createshape;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenu edit;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JPanel gw;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> list;
    private javax.swing.JTextArea logdata;
    private javax.swing.JTextField name;
    private javax.swing.JTextField newName;
    private javax.swing.JTextField newParam;
    private javax.swing.JMenuItem open;
    private javax.swing.JTextArea parameter;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem showfolder;
    private javax.swing.JMenuItem updateSession;
    private javax.swing.JTextField volume;
    // End of variables declaration//GEN-END:variables

}
